import type { Listing, Marketplace } from "./types";

/**
 * Realistic mock listing catalogue used by the MockMarketplaceProvider and as
 * a fallback for live providers without credentials.
 *
 * Imagery uses seeded picsum.photos URLs — safe, deterministic placeholders
 * with no marketplace ToS implications. Swap for real CDN images once a
 * licensed API integration is in place (see docs/INTEGRATION.md).
 *
 * `listedAt` values are anchored around 2026-07-29 so "time since listed" and
 * "newly listed" filters behave predictably in the demo.
 */

function img(seed: string, count = 2): string[] {
  return Array.from(
    { length: count },
    (_, i) => `https://picsum.photos/seed/${seed}-${i}/900/1100`,
  );
}

type RawListing = Omit<Listing, "id" | "currency" | "imageUrls"> & {
  currency?: string;
  imageSeed: string;
  imageCount?: number;
};

const RAW: RawListing[] = [
  // ───────────────────────── Chanel runners / sneakers ─────────────────────
  {
    marketplace: "grailed",
    externalId: "gr-chanel-01",
    title: "Chanel CC Logo Suede & Mesh Runner Sneakers",
    brand: "Chanel",
    category: "Sneakers",
    size: "US 9",
    condition: "Excellent",
    color: "Grey",
    gender: "Womenswear",
    price: 685,
    shippingPrice: 20,
    listingUrl: "https://www.grailed.com/listings/gr-chanel-01",
    description:
      "Iconic Chanel low-top runners in grey suede and mesh with interlocking CC logo at the side. Worn a handful of times, no visible flaws. Comes with dust bag.",
    sellerName: "archive_atelier",
    sellerRating: 4.9,
    sellerVerified: true,
    location: "Paris, FR",
    listedAt: "2026-07-27T10:00:00Z",
    imageSeed: "chanel-runner-grey",
    imageCount: 3,
  },
  {
    marketplace: "ebay",
    externalId: "eb-chanel-02",
    title: "CHANEL Trainer Sneakers Low Top Runners Black White",
    brand: "Chanel",
    category: "Sneakers",
    size: "US 8",
    condition: "Good",
    color: "Black",
    gender: "Womenswear",
    price: 599,
    shippingPrice: 0,
    freeShipping: true,
    listingUrl: "https://www.ebay.com/itm/eb-chanel-02",
    description:
      "Authentic Chanel runner trainers, black and white colourway. Light wear to sole, uppers clean. Sold as-is, authenticity guaranteed.",
    sellerName: "luxe_resale_co",
    sellerRating: 4.7,
    sellerVerified: true,
    location: "New York, US",
    listedAt: "2026-07-25T14:30:00Z",
    imageSeed: "chanel-runner-black",
  },

  // ───────────────────── Carhartt double-knee pants ────────────────────────
  {
    marketplace: "grailed",
    externalId: "gr-carhartt-04",
    title: "Carhartt WIP Double Knee Ruck Single Knee Pant Hamilton Brown",
    brand: "Carhartt",
    category: "Pants",
    size: "34x32",
    condition: "Excellent",
    color: "Brown",
    gender: "Menswear",
    price: 78,
    shippingPrice: 12,
    listingUrl: "https://www.grailed.com/listings/gr-carhartt-04",
    description:
      "Carhartt WIP double knee work pant in Hamilton Brown duck canvas. Broken-in but structurally perfect. Utility pockets intact.",
    sellerName: "workwear_archive",
    sellerRating: 4.8,
    sellerVerified: true,
    location: "Portland, US",
    listedAt: "2026-07-26T16:45:00Z",
    imageSeed: "carhartt-dk-brown",
    imageCount: 3,
  },
  {
    marketplace: "ebay",
    externalId: "eb-carhartt-05",
    title: "Carhartt Double Knee Dungaree Work Pants Carpenter Tan 36x30",
    brand: "Carhartt",
    category: "Pants",
    size: "36x30",
    condition: "Good",
    color: "Tan",
    gender: "Menswear",
    price: 52,
    shippingPrice: 9.5,
    listingUrl: "https://www.ebay.com/itm/eb-carhartt-05",
    description:
      "Vintage Carhartt double-knee dungaree in tan. Honest fading and workwear patina. Measured 35.5 waist, 30 inseam.",
    sellerName: "midwest_thrift",
    sellerRating: 4.5,
    sellerVerified: false,
    location: "Chicago, US",
    listedAt: "2026-07-24T11:00:00Z",
    imageSeed: "carhartt-dk-tan",
  },
  {
    marketplace: "grailed",
    externalId: "gr-carhartt-07",
    title: "Carhartt WIP Double Knee Pant Dearborn Canvas Wax Green",
    brand: "Carhartt",
    category: "Pants",
    size: "30x30",
    condition: "New with tags",
    color: "Green",
    gender: "Menswear",
    price: 120,
    shippingPrice: 10,
    listingUrl: "https://www.grailed.com/listings/gr-carhartt-07",
    description:
      "Brand new with tags. Dearborn canvas, wax green colourway. Triple-stitched, reinforced double knee. Current season.",
    sellerName: "workwear_archive",
    sellerRating: 4.8,
    sellerVerified: true,
    location: "Portland, US",
    listedAt: "2026-07-28T19:30:00Z",
    imageSeed: "carhartt-dk-green",
  },

  // ───────────────────── Balenciaga sneakers / 3XL ─────────────────────────
  {
    marketplace: "grailed",
    externalId: "gr-bal-08",
    title: "Balenciaga Triple S 3XL Sneaker Black Distressed",
    brand: "Balenciaga",
    category: "Sneakers",
    size: "EU 42",
    condition: "Good",
    color: "Black",
    gender: "Menswear",
    price: 420,
    shippingPrice: 25,
    listingUrl: "https://www.grailed.com/listings/gr-bal-08",
    description:
      "Balenciaga 3XL chunky runner in triple black. Some creasing and sole discoloration consistent with wear. Still a statement piece.",
    sellerName: "hype_archive",
    sellerRating: 4.4,
    sellerVerified: true,
    location: "Los Angeles, US",
    listedAt: "2026-07-23T13:20:00Z",
    imageSeed: "balenciaga-3xl-black",
    imageCount: 3,
  },
  {
    marketplace: "ebay",
    externalId: "eb-bal-09",
    title: "Balenciaga 3XL Sneakers Worn Look White Grey Mens EU 44",
    brand: "Balenciaga",
    category: "Sneakers",
    size: "EU 44",
    condition: "Excellent",
    color: "White",
    gender: "Menswear",
    price: 690,
    shippingPrice: 18,
    listingUrl: "https://www.ebay.com/itm/eb-bal-09",
    description:
      "Balenciaga 3XL trainers in the worn-look white/grey. Excellent pre-owned condition, includes box and extra laces.",
    sellerName: "designer_plug",
    sellerRating: 4.8,
    sellerVerified: true,
    location: "Miami, US",
    listedAt: "2026-07-27T20:10:00Z",
    imageSeed: "balenciaga-3xl-white",
  },

  // ─────────────────────── Vintage Levi's 501 ─────────────────────────────
  {
    marketplace: "ebay",
    externalId: "eb-levis-11",
    title: "Vintage Levi's 501 Jeans Made in USA Medium Wash 33x32",
    brand: "Levi's",
    category: "Jeans",
    size: "33x32",
    condition: "Good",
    color: "Blue",
    gender: "Menswear",
    price: 68,
    shippingPrice: 11,
    listingUrl: "https://www.ebay.com/itm/eb-levis-11",
    description:
      "Vintage 90s Levi's 501 made in USA. Medium wash, honest fades, button fly. Measures 32.5 waist, 31.5 inseam.",
    sellerName: "denim_dispatch",
    sellerRating: 4.7,
    sellerVerified: true,
    location: "Austin, US",
    listedAt: "2026-07-26T09:30:00Z",
    imageSeed: "levis-501-medium",
    imageCount: 3,
  },
  {
    marketplace: "grailed",
    externalId: "gr-levis-12",
    title: "Vintage Levi's 501 Dark Wash Selvedge Redline 32x30",
    brand: "Levi's",
    category: "Jeans",
    size: "32x30",
    condition: "Excellent",
    color: "Indigo",
    gender: "Menswear",
    price: 145,
    shippingPrice: 14,
    listingUrl: "https://www.grailed.com/listings/gr-levis-12",
    description:
      "Rare redline selvedge 501s, dark indigo. Minimal wear, deep saturated colour. A grail for raw denim heads.",
    sellerName: "raw_denim_archive",
    sellerRating: 4.9,
    sellerVerified: true,
    location: "Tokyo, JP",
    listedAt: "2026-07-28T22:00:00Z",
    imageSeed: "levis-501-selvedge",
  },
  {
    marketplace: "ebay",
    externalId: "eb-levis-14",
    title: "Levi's 501 Black Vintage Faded Jeans 34x34 Straight",
    brand: "Levi's",
    category: "Jeans",
    size: "34x34",
    condition: "Fair",
    color: "Black",
    gender: "Menswear",
    price: 39,
    shippingPrice: 10,
    listingUrl: "https://www.ebay.com/itm/eb-levis-14",
    description:
      "Faded black 501s with plenty of vintage character. Wear at hems and pocket edges. Priced accordingly.",
    sellerName: "thrift_king_99",
    sellerRating: 4.3,
    sellerVerified: false,
    location: "Cleveland, US",
    listedAt: "2026-07-20T15:00:00Z",
    imageSeed: "levis-501-black",
  },

  // ────────────────────── Chrome Hearts hoodie ────────────────────────────
  {
    marketplace: "grailed",
    externalId: "gr-ch-15",
    title: "Chrome Hearts Cross Patch Pullover Hoodie Black L",
    brand: "Chrome Hearts",
    category: "Hoodies",
    size: "L",
    condition: "Excellent",
    color: "Black",
    gender: "Unisex",
    price: 1250,
    shippingPrice: 25,
    listingUrl: "https://www.grailed.com/listings/gr-ch-15",
    description:
      "Chrome Hearts black pullover hoodie with cross patch pocket and horseshoe logo back print. Excellent condition, authenticated.",
    sellerName: "grail_authenticated",
    sellerRating: 5.0,
    sellerVerified: true,
    location: "New York, US",
    listedAt: "2026-07-27T18:00:00Z",
    imageSeed: "chrome-hearts-hoodie-black",
    imageCount: 3,
  },
  {
    marketplace: "ebay",
    externalId: "eb-ch-16",
    title: "Chrome Hearts Zip Up Hoodie Grey Dagger Zipper Medium",
    brand: "Chrome Hearts",
    category: "Hoodies",
    size: "M",
    condition: "Good",
    color: "Grey",
    gender: "Unisex",
    price: 1490,
    shippingPrice: 0,
    freeShipping: true,
    listingUrl: "https://www.ebay.com/itm/eb-ch-16",
    description:
      "Grey Chrome Hearts zip hoodie with signature dagger zipper pull. Some fading from wash, no damage. Authenticity guaranteed.",
    sellerName: "luxe_resale_co",
    sellerRating: 4.7,
    sellerVerified: true,
    location: "New York, US",
    listedAt: "2026-07-25T12:00:00Z",
    imageSeed: "chrome-hearts-hoodie-grey",
  },

  // ──────────────── Maison Margiela GAT (German Army Trainer) ──────────────
  {
    marketplace: "grailed",
    externalId: "gr-mmm-18",
    title: "Maison Margiela Replica GAT German Army Trainer White",
    brand: "Maison Margiela",
    category: "Sneakers",
    size: "EU 43",
    condition: "Excellent",
    color: "White",
    gender: "Menswear",
    price: 340,
    shippingPrice: 18,
    listingUrl: "https://www.grailed.com/listings/gr-mmm-18",
    description:
      "Margiela Replica GATs in white leather and suede. Lightly worn, clean soles, includes box and cards.",
    sellerName: "minimal_wardrobe",
    sellerRating: 4.9,
    sellerVerified: true,
    location: "Antwerp, BE",
    listedAt: "2026-07-28T11:45:00Z",
    imageSeed: "margiela-gat-white",
    imageCount: 3,
  },
  {
    marketplace: "ebay",
    externalId: "eb-mmm-19",
    title: "Maison Margiela GAT Sneakers Grey Suede Mens EU 41",
    brand: "Maison Margiela",
    category: "Sneakers",
    size: "EU 41",
    condition: "Good",
    color: "Grey",
    gender: "Menswear",
    price: 265,
    shippingPrice: 15,
    listingUrl: "https://www.ebay.com/itm/eb-mmm-19",
    description:
      "Grey suede Margiela German Army Trainers. Good used condition with some scuffing to toe. Comfortable everyday grail.",
    sellerName: "designer_plug",
    sellerRating: 4.8,
    sellerVerified: true,
    location: "Miami, US",
    listedAt: "2026-07-23T17:15:00Z",
    imageSeed: "margiela-gat-grey",
  },

  // ─────────────────────── Broader catalogue depth ────────────────────────
  {
    marketplace: "grailed",
    externalId: "gr-misc-21",
    title: "Stone Island Garment Dyed Overshirt Olive M",
    brand: "Stone Island",
    category: "Jackets",
    size: "M",
    condition: "Excellent",
    color: "Green",
    gender: "Menswear",
    price: 295,
    shippingPrice: 16,
    listingUrl: "https://www.grailed.com/listings/gr-misc-21",
    description:
      "Stone Island garment-dyed overshirt in olive with signature compass badge. Excellent condition, badge intact.",
    sellerName: "euro_menswear",
    sellerRating: 4.8,
    sellerVerified: true,
    location: "Milan, IT",
    listedAt: "2026-07-26T14:00:00Z",
    imageSeed: "stone-island-olive",
  },
  {
    marketplace: "ebay",
    externalId: "eb-misc-23",
    title: "The North Face Nuptse 700 Puffer Jacket Black L",
    brand: "The North Face",
    category: "Jackets",
    size: "L",
    condition: "Good",
    color: "Black",
    gender: "Menswear",
    price: 130,
    shippingPrice: 0,
    freeShipping: true,
    listingUrl: "https://www.ebay.com/itm/eb-misc-23",
    description:
      "TNF Nuptse 700-fill puffer in black. Warm, no rips or down loss. Small logo wear. Great winter grail.",
    sellerName: "outdoor_resale",
    sellerRating: 4.6,
    sellerVerified: true,
    location: "Denver, US",
    listedAt: "2026-07-24T13:00:00Z",
    imageSeed: "tnf-nuptse-black",
  },
  {
    marketplace: "grailed",
    externalId: "gr-misc-24",
    title: "Rick Owens DRKSHDW Ramones Sneakers Black EU 42",
    brand: "Rick Owens",
    category: "Sneakers",
    size: "EU 42",
    condition: "Excellent",
    color: "Black",
    gender: "Menswear",
    price: 410,
    shippingPrice: 20,
    listingUrl: "https://www.grailed.com/listings/gr-misc-24",
    description:
      "Rick Owens DRKSHDW Ramones high-top in black canvas. Barely worn, clean throughout. Includes box.",
    sellerName: "avant_archive",
    sellerRating: 4.9,
    sellerVerified: true,
    location: "Berlin, DE",
    listedAt: "2026-07-27T16:30:00Z",
    imageSeed: "rick-ramones-black",
  },
  {
    marketplace: "ebay",
    externalId: "eb-misc-26",
    title: "Nike x Off-White Air Force 1 Volt Mens US 10",
    brand: "Nike",
    category: "Sneakers",
    size: "US 10",
    condition: "Good",
    color: "Volt",
    gender: "Menswear",
    price: 520,
    shippingPrice: 15,
    listingUrl: "https://www.ebay.com/itm/eb-misc-26",
    description:
      "Off-White AF1 in Volt. Worn but well cared for, all accessories included. Authenticity guaranteed by seller.",
    sellerName: "hype_archive",
    sellerRating: 4.4,
    sellerVerified: true,
    location: "Los Angeles, US",
    listedAt: "2026-07-22T18:45:00Z",
    imageSeed: "offwhite-af1-volt",
  },
  {
    marketplace: "grailed",
    externalId: "gr-misc-27",
    title: "Acne Studios Face Logo Wool Scarf Grey",
    brand: "Acne Studios",
    category: "Accessories",
    size: "One Size",
    condition: "New with tags",
    color: "Grey",
    gender: "Unisex",
    price: 175,
    shippingPrice: 10,
    listingUrl: "https://www.grailed.com/listings/gr-misc-27",
    description:
      "Acne Studios oversized wool scarf in grey melange with tonal face patch. New with tags, never worn.",
    sellerName: "minimal_wardrobe",
    sellerRating: 4.9,
    sellerVerified: true,
    location: "Antwerp, BE",
    listedAt: "2026-07-29T05:30:00Z",
    imageSeed: "acne-scarf-grey",
  },
  {
    marketplace: "ebay",
    externalId: "eb-misc-29",
    title: "Polo Ralph Lauren Vintage Fleece Sweater Cream XL",
    brand: "Ralph Lauren",
    category: "Sweaters",
    size: "XL",
    condition: "Good",
    color: "Cream",
    gender: "Menswear",
    price: 62,
    shippingPrice: 12,
    listingUrl: "https://www.ebay.com/itm/eb-misc-29",
    description:
      "Vintage Polo Ralph Lauren fleece in cream with pony logo. Cozy, no pilling. Oversized XL fit.",
    sellerName: "midwest_thrift",
    sellerRating: 4.5,
    sellerVerified: false,
    location: "Chicago, US",
    listedAt: "2026-07-23T09:50:00Z",
    imageSeed: "polo-fleece-cream",
  },
  {
    marketplace: "grailed",
    externalId: "gr-misc-30",
    title: "Comme des Garçons PLAY Heart Logo Cardigan Navy M",
    brand: "Comme des Garçons",
    category: "Sweaters",
    size: "M",
    condition: "Excellent",
    color: "Navy",
    gender: "Unisex",
    price: 210,
    shippingPrice: 14,
    listingUrl: "https://www.grailed.com/listings/gr-misc-30",
    description:
      "CDG PLAY heart-logo cardigan in navy wool. Excellent condition, all buttons present. Timeless staple.",
    sellerName: "euro_menswear",
    sellerRating: 4.8,
    sellerVerified: true,
    location: "Milan, IT",
    listedAt: "2026-07-27T15:10:00Z",
    imageSeed: "cdg-play-navy",
  },
  {
    marketplace: "ebay",
    externalId: "eb-misc-32",
    title: "Jordan 1 Retro High OG Chicago 2022 Mens US 11",
    brand: "Jordan",
    category: "Sneakers",
    size: "US 11",
    condition: "New with tags",
    color: "Red",
    gender: "Menswear",
    price: 430,
    shippingPrice: 0,
    freeShipping: true,
    listingUrl: "https://www.ebay.com/itm/eb-misc-32",
    description:
      "Deadstock Jordan 1 High Chicago 2022. Brand new, never worn, original box and all tags. Authenticity guaranteed.",
    sellerName: "designer_plug",
    sellerRating: 4.8,
    sellerVerified: true,
    location: "Miami, US",
    listedAt: "2026-07-25T19:00:00Z",
    imageSeed: "jordan1-chicago",
  },
  {
    marketplace: "grailed",
    externalId: "gr-misc-33",
    title: "Undercover Bauhaus Wool Coat Charcoal 2",
    brand: "Undercover",
    category: "Coats",
    size: "M",
    condition: "Excellent",
    color: "Charcoal",
    gender: "Menswear",
    price: 680,
    shippingPrice: 30,
    listingUrl: "https://www.grailed.com/listings/gr-misc-33",
    description:
      "Undercover archive wool coat in charcoal, size 2. Excellent condition, fully lined. A collector's piece.",
    sellerName: "avant_archive",
    sellerRating: 4.9,
    sellerVerified: true,
    location: "Berlin, DE",
    listedAt: "2026-07-24T22:15:00Z",
    imageSeed: "undercover-coat-charcoal",
  },
  {
    marketplace: "ebay",
    externalId: "eb-misc-35",
    title: "Vintage Champion Reverse Weave Hoodie Navy XL",
    brand: "Champion",
    category: "Hoodies",
    size: "XL",
    condition: "Good",
    color: "Navy",
    gender: "Unisex",
    price: 58,
    shippingPrice: 10,
    listingUrl: "https://www.ebay.com/itm/eb-misc-35",
    description:
      "90s Champion Reverse Weave hoodie in navy. Heavyweight, minimal fading, script logo. True vintage XL.",
    sellerName: "denim_dispatch",
    sellerRating: 4.7,
    sellerVerified: true,
    location: "Austin, US",
    listedAt: "2026-07-22T11:30:00Z",
    imageSeed: "champion-hoodie-navy",
  },
  {
    marketplace: "grailed",
    externalId: "gr-misc-36",
    title: "Our Legacy Box Shirt Silk Blend Ivory 48",
    brand: "Our Legacy",
    category: "Shirts",
    size: "M",
    condition: "New without tags",
    color: "Ivory",
    gender: "Menswear",
    price: 230,
    shippingPrice: 15,
    listingUrl: "https://www.grailed.com/listings/gr-misc-36",
    description:
      "Our Legacy Box Shirt in ivory silk blend, size 48. Never worn, no tags. Boxy relaxed silhouette.",
    sellerName: "minimal_wardrobe",
    sellerRating: 4.9,
    sellerVerified: true,
    location: "Antwerp, BE",
    listedAt: "2026-07-28T17:40:00Z",
    imageSeed: "our-legacy-box-ivory",
  },
];

export const MOCK_LISTINGS: Listing[] = RAW.map((raw) => {
  const { imageSeed, imageCount, currency, ...rest } = raw;
  return {
    ...rest,
    id: `${raw.marketplace}:${raw.externalId}`,
    currency: currency ?? "USD",
    imageUrls: img(imageSeed, imageCount ?? 2),
  };
});

export function mockListingsFor(marketplace: Marketplace): Listing[] {
  return MOCK_LISTINGS.filter((l) => l.marketplace === marketplace);
}
